package br.edu.ifba.inf0008.uniEvents.services;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.LinkedHashMap;

import br.edu.ifba.inf0008.uniEvents.model.events.Event;
import br.edu.ifba.inf0008.uniEvents.model.participants.Participant;
import br.edu.ifba.inf0008.uniEvents.utils.Lines;


public class ReportsManager {
  private static final DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");

  public String generateReport(LinkedHashMap<String, Event> events, String reportTitle, Boolean isDetailed) {
    StringBuilder report = new StringBuilder();
    report.append(Lines.doubleLine()).append("\n");
    report.append(Lines.titleLine(String.format("Report: %s", reportTitle))).append("\n");
    report.append(Lines.titleLine(String.format("Created at: %s", LocalDateTime.now().format(DATE_TIME_FORMATTER)))).append("\n");
    report.append(Lines.titleLine("Generated by: UniEvents")).append("\n");
    report.append(Lines.doubleLine()).append("\n");
    report.append(Lines.titleLine("Events List")).append("\n");
    report.append(Lines.doubleLine()).append("\n");
    if(events.isEmpty()){
      report.append(Lines.leftText("No events found for this report.")).append("\n");
    } else {
      for (Event event : events.values()) {
        report.append(Lines.straightLine()).append("\n");
        report.append(event.toString());
        if(isDetailed && !event.getParticipants().isEmpty()){
          report.append(Lines.leftText("")).append("\n");
          report.append(Lines.leftText("Participant Details:")).append("\n");
          for(Participant participant: event.getParticipants().values()){
            report.append(Lines.mixedLines()).append("\n");
            report.append(Lines.leftText(String.format("    Participant: %s", participant.getName()))).append("\n");
            report.append(Lines.leftText(String.format("    CPF: %s", participant.getCpf()))).append("\n");
            report.append(Lines.leftText(String.format("    Email: %s", participant.getEmail()))).append("\n");
            report.append(Lines.leftText(String.format("    Phone: %s", participant.getPhone()))).append("\n");
            report.append(Lines.leftText(String.format("    Birthdate: %s", participant.getBirthDate().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"))))).append("\n");
          }
        }
        report.append(Lines.straightLine()).append("\n");
      }
    }
    report.append(Lines.doubleLine()).append("\n");
    report.append(Lines.titleLine("End of Report")).append("\n");
    report.append(Lines.doubleLine());
    report.append("\n");
    return report.toString();
  }
}