package br.edu.ifba.inf0008.uniEvents.services.generators;

import java.time.LocalDateTime;
import java.util.List;

import br.edu.ifba.inf0008.uniEvents.model.events.Event;
import br.edu.ifba.inf0008.uniEvents.model.participants.Participant;
import br.edu.ifba.inf0008.uniEvents.utils.Colors;
import br.edu.ifba.inf0008.uniEvents.utils.Lines;
import br.edu.ifba.inf0008.uniEvents.utils.Utils;


public class ReportsGenerator {
  public static String generateReport(List<Event> events, String reportTitle, Boolean isDetailed) {
    StringBuilder report = new StringBuilder();
    report.append(Lines.doubleLine()).append("\n");
    report.append(Lines.centeredMultiLineText(String.format("%s", reportTitle))).append("\n");
    report.append(Lines.centeredMultiLineText(String.format("Created at: %s", Utils.dateToString(LocalDateTime.now())))).append("\n");
    report.append(Lines.centeredMultiLineText("Generated by: UniEvents")).append("\n");
    report.append(Lines.doubleLine()).append("\n");
    report.append(Lines.centeredMultiLineText("Events List")).append("\n");
    report.append(Lines.doubleLine()).append("\n");
    if(events.isEmpty()){
      report.append(Lines.multiLineText("No events found for this report.")).append("\n");
    } else {
      for (Event event : events) {
        report.append(eventSummary(event, isDetailed));
      }
    }
    report.append(Lines.doubleLine()).append("\n");
    report.append(Lines.centeredMultiLineText("End of Report")).append("\n");
    report.append(Lines.doubleLine());
    report.append("\n");
    return report.toString();
  }

  public static String eventSummary(Event event, Boolean isDetailed){
    StringBuilder report = new StringBuilder();
    report.append(Lines.doubleLine()).append("\n");
    report.append(Lines.centeredMultiLineText("Event: " + event.getType(), Colors.YELLOW_BOLD)).append("\n");
    report.append(Lines.doubleLine()).append("\n");
    report.append(Lines.straightLine()).append("\n");
    report.append(event.toString());
    report.append(Lines.straightLine()).append("\n");
    if(isDetailed && !event.getParticipants().isEmpty()){
      report.append(Lines.mixedLines()).append("\n");
      report.append(Lines.centeredMultiLineText("Participants in (" + event.getCode() + ")", Colors.BLUE_BOLD)).append("\n");
      report.append(Lines.mixedLines()).append("\n");
      for(Participant participant : event.getParticipants().values()){
        report.append(participantSummary(participant));
      }
      report.append(Lines.mixedLines()).append("\n");
    }
    return report.toString();
  }

  public static String participantSummary(Participant participant){
    StringBuilder report = new StringBuilder();
    report.append(Lines.doubleLine()).append("\n");
    report.append(Lines.centeredMultiLineText("Participant: " + participant.getType(), Colors.BLUE_BOLD)).append("\n");
    report.append(Lines.doubleLine()).append("\n");
    report.append(Lines.straightLine()).append("\n");
    report.append(participant.toString());
    report.append(Lines.straightLine()).append("\n");
    return report.toString();
  }
}